openapi: 3.2.0
info:
  title: ButterflyMX Access Points API
  version: v4
servers:
- description: Production
  url: https://api.butterflymx.com
- description: Sandbox
  url: https://api.na.sandbox.butterflymx.com
- description: Other environment
  url: https://{environment_name}.butterflymx.com
  variables:
    environment_name:
      default: foobar
tags:
- name: Access Points
paths:
  /v4/access_points:
    get:
      summary: list access points
      tags:
      - Access Points
      description: 'An **Access Point** is any one, or a set of, doors, ramps, gates, entrances or

        exits that behave as a single entity.


        An Access Point can be one physical door, but in the case of a vestibule

        or a mantrap, it can be two doors that are controlled together.


        Through Access Points one can manage access across the system

        and exercise control over physical doors.

        '
      security:
      - Bearer: []
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          minimum: 0
        description: requested page
        example: 3
      - name: per
        in: query
        schema:
          type: integer
          minimum: 1
          maximum: 100
        description: page size
        example: 50
      - name: q[name_eq]
        in: query
        description: filter by exact match on name (case insensitive)
        example: A003
        schema:
          type: string
      - name: q[name_start]
        in: query
        description: filter by name starts with (case insensitive)
        example: A
        schema:
          type: string
      - name: q[building_id_eq]
        in: query
        description: filter by exact match on building id
        example: 123
        schema:
          type: string
      - name: q[building_id_in][]
        in: query
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
        description: filter by building id in list
        example:
        - 123
        - 456
      - name: q[id_in][]
        in: query
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
        description: filter by id in list
        example:
        - 123
        - 456
      responses:
        '200':
          description: fetch all access points that your user can see
          content:
            application/json:
              examples:
                fetch all access points that your user can see:
                  value:
                    data:
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 22177636
                      name: Back door
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids:
                      - 708353660
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 157533314
                      name: Rooftop
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids:
                      - 94566002
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 164770902
                      name: Package room
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids:
                      - 566540595
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 232149205
                      name: Middle door
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids:
                      - 708353660
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 239674119
                      name: Front Entrance
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 505753268
                      device_ids:
                      - 127952958
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 259697296
                      name: Ball room
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids: []
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 649822440
                      name: Front Delivery Entrance
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 505753268
                      device_ids:
                      - 127952958
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 834074842
                      name: Main gate
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 750989427
                      device_ids: []
                      open_hours: []
                    - created_at: '2026-06-17T15:12:20Z'
                      id: 842395203
                      name: Front door
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 577696272
                      device_ids:
                      - 708353660
                      - 408919060
                      open_hours: []
                    page_info:
                      current_page: 1
                      total_pages: 1
                      total_item_count: 9
                      page_item_count: 9
                      page_size: 50
                      next_page: null
                      prev_page: null
                      first_page: true
                      last_page: true
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    errors:
                    - field: base
                      code: unauthorized
                      messages: Unauthorized
  /v4/access_points/{id}:
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show access point
      tags:
      - Access Points
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    data:
                      created_at: '2026-06-17T15:12:20Z'
                      id: 239674119
                      name: Front Entrance
                      updated_at: '2026-06-17T15:12:20Z'
                      building_id: 505753268
                      device_ids:
                      - 127952958
                      open_hours: []
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    errors:
                    - field: base
                      code: unauthorized
                      messages: Unauthorized
  /v4/access_points/{id}/schedules:
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    - name: page
      in: query
      schema:
        type: integer
        minimum: 0
      description: requested page
      example: 3
    - name: per
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
      description: page size
      example: 50
    get:
      summary: show schedules
      tags:
      - Access Points
      security:
      - Bearer: []
      description: 'Times during which this access point can be used by current user.

        '
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    data:
                    - id: 83723449
                      weekdays:
                      - mon
                      - tue
                      - wed
                      - thu
                      - fri
                      - sat
                      - sun
                      from: 00:00
                      to: 00:00
                    page_info:
                      current_page: 1
                      total_pages: 1
                      total_item_count: 1
                      page_item_count: 1
                      page_size: 50
                      next_page: null
                      prev_page: null
                      first_page: true
                      last_page: true
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    errors:
                    - field: base
                      code: unauthorized
                      messages: Unauthorized
components:
  securitySchemes:
    Bearer:
      description: JWT necessary to make API calls
      type: apiKey
      name: Authorization
      in: header
